"""add indexes to feature_flags

Revision ID: 112a72352ff0
Revises: 2ea00952483a
Create Date: 2026-07-30 15:02:13.146997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112a72352ff0'
down_revision: Union[str, Sequence[str], None] = '2ea00952483a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feature_flags_environment_id'), 'feature_flags', ['environment_id'], unique=False)
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_environment_id'), table_name='feature_flags')
    # ### end Alembic commands ###
