"""add milestone 2 fields

Revision ID: b23430f288d8
Revises: 112a72352ff0
Create Date: 2026-08-16 17:50:16.703135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23430f288d8'
down_revision: Union[str, Sequence[str], None] = '112a72352ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('audit_log', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('audit_log', 'details',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.add_column('feature_flags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('feature_flags', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('feature_flags', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('flag_versions', sa.Column('old_value', sa.String(length=100), nullable=True))
    op.add_column('flag_versions', sa.Column('new_value', sa.String(length=100), nullable=True))
    op.add_column('flag_versions', sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('flag_versions', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('flag_versions', 'changed_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_flag_versions_id'), 'flag_versions', ['id'], unique=False)
    op.alter_column('targeting_rules', 'attribute',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('targeting_rules', 'operator',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('targeting_rules', 'value',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_targeting_rules_id'), 'targeting_rules', ['id'], unique=False)
    op.add_column('user_group_memberships', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('user_group_memberships', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_group_memberships', 'group_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_user_group_memberships_id'), 'user_group_memberships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_group_memberships_id'), table_name='user_group_memberships')
    op.alter_column('user_group_memberships', 'group_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_group_memberships', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user_group_memberships', 'created_at')
    op.drop_index(op.f('ix_targeting_rules_id'), table_name='targeting_rules')
    op.alter_column('targeting_rules', 'value',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('targeting_rules', 'operator',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('targeting_rules', 'attribute',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_flag_versions_id'), table_name='flag_versions')
    op.alter_column('flag_versions', 'changed_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('flag_versions', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('flag_versions', 'changed_at')
    op.drop_column('flag_versions', 'new_value')
    op.drop_column('flag_versions', 'old_value')
    op.alter_column('feature_flags', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('feature_flags', 'updated_at')
    op.drop_column('feature_flags', 'created_at')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.alter_column('audit_log', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_log', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('audit_log', 'created_at')
    # ### end Alembic commands ###
